
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./data/dynamodb-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    command: >
      -jar DynamoDBLocal.jar
      -sharedDb
      -dbPath ./data
